
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/element_admin?useSSL=false&serverTimezone=UTC
    username: root
    password: whc123

server:
    port: 8080

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.mall.entity
    configuration:
      map-underscore-to-camel-case: true